//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgtMerkez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurs()
        {
            this.KursOgrenci = new HashSet<KursOgrenci>();
        }
    
        public int KursID { get; set; }
        public string KursAd { get; set; }
        public string Aciklama { get; set; }
        public string Sure { get; set; }
        public Nullable<decimal> Ucret { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> ToplamSaat { get; set; }
    
        public virtual KursTipi KursTipi { get; set; }
        public virtual OgretimElemani OgretimElemani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursOgrenci> KursOgrenci { get; set; }
    }
}
